### ISSUE TITLE
Should save file to where it's told rather than to the OF data path

### ISSUE THREAD

**Issue by atduskgreg** [obviousjim/ofxSTL#1]
As you have it both ofxSTLASCIIWriter and ofxSTLBinaryWriter prepend "data/" to the filename they're give before saving. This makes it impossible to save an STL anywhere outside of the app's data folder -- for example at a location selected by the user in the file save dialog.

I have a pull request coming shortly that makes the change. For symmetry it also makes the equivalent change to the ofxSTLReader classes. And, of course, the example is update accordingly.

**Comment by obviousjim** [comment]
solved by 441a6872204f8bc4a7efe2fd02d58fd01673037d
